-- Create lessons table in Supabase
create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  discipline_id bigint not null references public.disciplines(id) on delete restrict,
  type text,
  teacher_id bigint not null references public.teachers(id) on delete restrict,
  audience_id bigint not null references public.audiences(id) on delete restrict,
  group_id bigint not null references public.groups(id) on delete cascade,
  pair_no integer not null,
  day_of_week integer not null,
  date timestamp with time zone not null,
  subgroup text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists idx_lessons_date on public.lessons(date);
create index if not exists idx_lessons_group_date on public.lessons(group_id, date);
create unique index if not exists uq_lessons_group_date_pair on public.lessons(group_id, date, pair_no, subgroup);

-- Row Level Security (optional): enable and allow authenticated read/write
alter table public.lessons enable row level security;
drop policy if exists lessons_select on public.lessons;
drop policy if exists lessons_insert on public.lessons;
drop policy if exists lessons_update on public.lessons;
drop policy if exists lessons_delete on public.lessons;

create policy lessons_select on public.lessons for select using (true);
create policy lessons_insert on public.lessons for insert with check (true);
create policy lessons_update on public.lessons for update using (true);
create policy lessons_delete on public.lessons for delete using (true);

