-- Создание таблицы audiences
CREATE TABLE IF NOT EXISTS audiences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL,
  capacity integer NOT NULL,
  boss text,
  building text,
  equipment jsonb,
  created_at timestamptz DEFAULT timezone('utc', now()),
  updated_at timestamptz DEFAULT timezone('utc', now()),
  deleted_at timestamptz,
  local_id integer,
  sync_status text DEFAULT 'synced',
  version integer DEFAULT 1
);

-- Создание индексов
CREATE INDEX IF NOT EXISTS idx_audiences_sync_status ON audiences(sync_status);
CREATE INDEX IF NOT EXISTS idx_audiences_local_id ON audiences(local_id);
CREATE INDEX IF NOT EXISTS idx_audiences_deleted_at ON audiences(deleted_at);

-- Включение RLS
ALTER TABLE audiences ENABLE ROW LEVEL SECURITY;

-- Политики безопасности
CREATE POLICY "Allow read access for authenticated users" 
ON audiences FOR SELECT TO authenticated 
USING (deleted_at IS NULL);

CREATE POLICY "Allow insert access for authenticated users" 
ON audiences FOR INSERT TO authenticated 
WITH CHECK (true);

CREATE POLICY "Allow update access for authenticated users" 
ON audiences FOR UPDATE TO authenticated 
USING (true) WITH CHECK (true);

-- Функция и триггер для updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS update_audiences_updated_at ON audiences;
CREATE TRIGGER update_audiences_updated_at
    BEFORE UPDATE ON audiences
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();